name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['8.x', '10.x', '12.x', '14.x']

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: install dependencies
      run: npm ci
    - if: matrix.node-version === '8.x' # yargs on ava needs at least node 10 as engine
      name: downgrade ava (node 8 only)
      run: npm i -D ava@3.12.1
    - name: build and test:
      run: |
        npm run build --if-present
        npm test
      env:
        CI: true
